### ISSUE TITLE
Please add support for signature() returning the MD5 signature of the uncompressed audio stream as read from the FLAC stream info header

### ISSUE THREAD

**Issue by audiomuze** [supermihi/pytaglib#107]
Having the md5 hash of a FLAC file is very useful for detecting duplicate files or folders containining multiple flac files that are collectively identical to the FLAC contents in another folder.  Adding support for taglib's FLAC signature() would enable the md5 to be readily accessed using pytaglib.

I imagine implementation would be along the lines of:

```
property md5sum:
        def __get__(self):
            self.check_closed()
            return self.cFile.audioProperties().signature()
```

**Comment by supermihi** [comment]
Hi @audiomuze,
while I see the value of accessing the FLAC signature, I have to reject this request: it would break the prinicple of this library, which is to only offer the common, file type-independent interface of taglib. `signature()` is not present in the [`TagLib::AudioProperties`](https://taglib.org/api/classTagLib_1_1AudioProperties.html) class but only the `FLAC::Properties` subclass.

**Comment by supermihi** [comment]
You can use [mutagen](https://mutagen.readthedocs.io/), though: the `mutagen.flac.StreamInfo` class appears to have an [`md5_signature`](https://github.com/quodlibet/mutagen/blob/master/mutagen/flac.py) field that should do exactly what you need.

**Comment by audiomuze** [comment]
Thanks, I'm aware of and have used mutagen.  In this instance I was specifically looking to switch to taglib because I'm intending to do bulk tag processing and want to maximise throughput.
