### ISSUE TITLE
Install failed on MacOs , python 3.7

### ISSUE THREAD

**Issue by Gandharthus** [supermihi/pytaglib#108]
Hello I have run the following commands on CLI zsh:
> Brew install taglib
>pip install pytaglib

I get the error :
src/taglib.cpp:732:10: fatal error: 'taglib/tstring.h' file not found

The full error goes as follows :
Preparing metadata (setup.py) ... done
Building wheels for collected packages: pytaglib
  Building wheel for pytaglib (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      file src/pytaglib.py (for module pytaglib) not found
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-37
      copying src/pyprinttags.py -> build/lib.macosx-10.9-x86_64-cpython-37
      file src/pytaglib.py (for module pytaglib) not found
      running build_ext
      building 'taglib' extension
      creating build/temp.macosx-10.9-x86_64-cpython-37
      creating build/temp.macosx-10.9-x86_64-cpython-37/src
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/Gandharthus/Documents/GitHub/Gandharthus/Last_v/venv/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/taglib.cpp -o build/temp.macosx-10.9-x86_64-cpython-37/src/taglib.o
      src/taglib.cpp:732:10: fatal error: 'taglib/tstring.h' file not found
      #include "taglib/tstring.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytaglib
  Running setup.py clean for pytaglib
Failed to build pytaglib
Installing collected packages: pytaglib
  Running setup.py install for pytaglib ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pytaglib did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running install
      /Users/Gandharthus/Documents/GitHub/Gandharthus/Last_v/venv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      file src/pytaglib.py (for module pytaglib) not found
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-37
      copying src/pyprinttags.py -> build/lib.macosx-10.9-x86_64-cpython-37
      file src/pytaglib.py (for module pytaglib) not found
      running build_ext
      building 'taglib' extension
      creating build/temp.macosx-10.9-x86_64-cpython-37
      creating build/temp.macosx-10.9-x86_64-cpython-37/src
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Users/Gandharthus/Documents/GitHub/Gandharthus/Last_v/venv/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/taglib.cpp -o build/temp.macosx-10.9-x86_64-cpython-37/src/taglib.o
      src/taglib.cpp:732:10: fatal error: 'taglib/tstring.h' file not found
      #include "taglib/tstring.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pytaglib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Gandharthus** [comment]
Hello, I think this is related to issue #105 .
I was able to fix it running :
pip install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-I/opt/homebrew/Cellar/taglib/1.12/include" --global-option="-L/usr/local/lib" --global-option="-L/opt/homebrew/Cellar/taglib/1.12/lib" pytaglib 

Very ugly workaround

**Comment by dennisdebel** [comment]
> pip install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-I/opt/homebrew/Cellar/taglib/1.12/include" --global-option="-L/usr/local/lib" --global-option="-L/opt/homebrew/Cellar/taglib/1.12/lib" pytaglib

This throws the following error:

```
      src/taglib.cpp:1287:10: fatal error: 'taglib/tstring.h' file not found
       1287 | #include "taglib/tstring.h"
            |          ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytaglib
Failed to build pytaglib
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> pytaglib
```
