### ISSUE TITLE
'src/taglib/tstring.h' file not found

### ISSUE THREAD

**Issue by hanhanhan** [supermihi/pytaglib#15]
On trying to install, using both the tarball and pip, I get a file not found error for tstring.h:

schlomo:pytaglib-1.0.3 han$ python3 setup.py build
running build
running build_py
creating build
creating build/lib.macosx-10.6-intel-3.4
copying src/pyprinttags.py -> build/lib.macosx-10.6-intel-3.4
running build_ext
building 'taglib' extension
creating build/temp.macosx-10.6-intel-3.4
creating build/temp.macosx-10.6-intel-3.4/src
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c src/taglib.cpp -o build/temp.macosx-10.6-intel-3.4/src/taglib.o
src/taglib.cpp:268:10: fatal error: 
      'taglib/tstring.h' file not found
#include "taglib/tstring.h"

**Comment by supermihi** [comment]
As noted in the README, you potentially need to tell `setup.py`where to find the taglib includes: try
```
    python setup.py build --include-dirs /path/to/your/taglib/headers
```

**Comment by qbuchanan** [comment]
On OS X here is how I fixed the issue

first use brew to install taglib

`    brew install taglib`

and then pass the locations of the taglib headers and library to pip

`    sudo pip install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib"  pytaglib`

**Comment by supermihi** [comment]
Thanks for sharing these command-line options for specifying a custom taglib directory directly to pip. I am currently preparing a small release in which I'll add these to the README.

Michael

**Comment by daesung** [comment]
In Installation Note
"If no binary packages exists, you need to have both Python and taglib installed with development headers (packages python3-dev (or python-dev) and libtag1-dev for debian / ubuntu and derivates,  python-devel and taglib-devel for fedora and friends, brew install taglib on OS X)."

so, on Ubuntu, 
sudo apt-get install libtag1-dev

**Comment by blairg23** [comment]
In the Pypi docs (https://pypi.python.org/pypi/pytaglib), there is a section at the bottom for how to install for Windows, if you're running that OS.

**Comment by odie5533** [comment]
The easiest way I found to solve this was to check the [download page](https://pypi.org/project/pytaglib/#files) to see what versions of Python the wheels were available for, and install a version of Python that matches. That way I can use the pre-compiled pytaglib.

**Comment by supermihi** [comment]
Yes, right now I have to manually generate & upload windows wheels and, since I am not using windows regularly, these tend to come quite late. I have just uploaded wheels for python 3.9, in case anyone subscribed to this issue is interested.

It is also possible to build yourself for windows (see [the readme](https://github.com/supermihi/pytaglib/#compilation-windows) but that's no fun, admittedly. ;-)
