### ISSUE TITLE
Saving read-only files that contain letters 'æ/ø/å' a UnicodeDecodeError is raised

### ISSUE THREAD

**Issue by AndreasHassing** [supermihi/pytaglib#21]
### Issue description
Using `pytaglib` for the first time today (with Python 2.7.9), and stumbled upon a l10n issue. If I have a read-only file that contains the letters 'æ/ø/å' and I try to change tags and save, a `UnicodeDecodeError` is raised, and not a helpful `OSError` message stating that the file is read-only.

### Expected behavior
When saving a file after altering any tags on a read-only file, that contains any of the letters 'æ/ø/å', `pytaglib` should warn the user that the file is read-only via a `OSError`.

### Actual behavior
```python
Python 2.7.9 (default, Mar  8 2015, 00:52:26)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import taglib
>>> video = taglib.File("Adams Æbler Trailer.mp4")
>>> video.tags
{u'TITLE': [u'Adams Apples Adams \xe6bler Trailer']}
>>> video.tags["TITLE"] = [u"Adams \xe6bler Trailer"]
{u'TITLE': [u'Adams \xe6bler Trailer']}
>>> video.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/taglib.pyx", line 122, in taglib.File.save (src/taglib.cpp:1918)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
```

The issue seems to originate from the following line: https://github.com/supermihi/pytaglib/blob/eed722c5453c129bd931d9cbeb4bb9721cc49fc6/src/taglib.pyx#L122, where (apparently) only ASCII characters are allowed in the string format argument (i.e. the path).

**Comment by supermihi** [comment]
Hi Andreas,
thank you for reporting this. The latest commit should fix the issue, could you please test if it indeed does?
Thanks,
Michael
