### ISSUE TITLE
does not find the include 

### ISSUE THREAD

**Issue by abeltre1** [supermihi/pytaglib#25]
~/Downloads/pytaglib-master $ python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying src/pyprinttags.py -> build/lib.linux-x86_64-2.7
running build_ext
building 'taglib' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/taglib.cpp -o build/temp.linux-x86_64-2.7/src/taglib.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
src/taglib.cpp:302:28: fatal error: taglib/tstring.h: No such file or directory
 #include "taglib/tstring.h"
                            ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by supermihi** [comment]
Hi,
you need to have taglib and its development headers installed before building pytaglib (package `libtag1-dev` if you are on debian/ubuntu).

**Comment by abeltre1** [comment]
Hello There,

Thank you!

Angel


Angel Beltre


On Wed, Aug 17, 2016 at 12:46 PM, Michael Helmling <notifications@github.com

**Comment by supermihi** [comment]
You're welcome – did that solve your problem? Then I'd close this issue.

**Comment by abeltre1** [comment]
Yes it did
