### ISSUE TITLE
Typo in examples

### ISSUE THREAD

**Issue by CarstenGrohmann** [supermihi/pytaglib#26]
There is a small typo in your example (README.md and README.txt). `retval` sould be `returnvalue`.

**Current (and erroneous):**
```
>>> returnvalue = song.save()
>>> retval
{}
```

**Fixed:**
```
>>> returnvalue = song.save()
>>> returnvalue
{}
```

**Comment by supermihi** [comment]
Thank you for the report and sorry for the delay (I've been offline for a week). Fixed now.
