### ISSUE TITLE
Pytaglib 1.30 installer cannot find 'taglib/tstring.h' taglib 1.11.1 or taglib 1.11

### ISSUE THREAD

**Issue by TheSwar3** [supermihi/pytaglib#27]
In building/installing pytaglib from instructions on https://pypi.python.org/pypi/pytaglib got error from setup.py build and setup.py install: "src\taglib.cpp<302>: fatal error C1083: Cannot open include file: 'taglib/tstring.h".

Indeed no such file appears to exist.  Tried with both taglib 1.11.1 and 1.11.

![image](https://cloud.githubusercontent.com/assets/23299322/20041453/315eaa42-a4ce-11e6-927e-ee514ec8fe3f.png)

For what its worth I also tried with pip:
![image](https://cloud.githubusercontent.com/assets/23299322/20041566/170d17da-a4d0-11e6-9484-da17326d8e59.png)

**Comment by TheSwar3** [comment]
Never mind, had wrong install directory had /install not /taglib-install.  Took directions too literally.

**Comment by supermihi** [comment]
Ok, glad you could solve the issue! :)
