### ISSUE TITLE
Unicode filenames cannot be opened on Windows

### ISSUE THREAD

**Issue by spiritualized** [supermihi/pytaglib#28]
Any path containing non-ascii characters seems to be unopenable under Windows. Occurring with a freshly compiled pytaglib under Python 3.5.2. To reproduce, simply create a file containing any unusual characters (anything in Cyrillic should suffice) and attempt to open it.

Stack trace below:

  File "example.py", line 338, in check_tags
    tracks[i] = taglib.File(os.path.join(folder, i))
  File "src/taglib.pyx", line 74, in taglib.File.__cinit__ (src\taglib.cpp:1360)
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

**Comment by supermihi** [comment]
Thank you for your report and sorry for me not answering until now. I can reproduce your problem, but don't yet fully understand how to solve it. According to `sys.getfilesystemencoding()` (and Python's documentation), `mbcs` *is* the encoding that should be used when accessing filenames as `bytes` on windows, but it cannod represent characters which are not in the local codepage. Using other encodings such as `utf-16-le` (which actually is the native filesystem encoding on Windows NT +) does not work either.

I'll try to dig further as soon as I find some time, sorry but you might need some patience ...

**Comment by spiritualized** [comment]
I tried monkeypatching `sys.getfilesystemencoding()` and came to a similar conclusion to you. Further experimentation is proving difficult - rebuilds of the library don't seem to be reflecting changes to taglib.pyx. Is there an unusual folder I need to purge in order to guarantee a full rebuild?

**Comment by supermihi** [comment]
Deleting the generated `taglib.cpp` file or using the `--cython` switch to `setup.py` should do the trick. 

I think I found the solution: The [create](https://github.com/taglib/taglib/blob/master/taglib/fileref.h#L273) method takes a `FileName` parameter, which is conditionally typedef'ed to `const char*` on non-windows systems but defined as a class with both a `const char*` and a `const wchar_t*` constructor on windows. When calling the `wchar_t` version, I can open arbitrary files without errors (with the nice side effect that Cython automatically converts python unicode strings to `wchar_t`, which completely eliminates the need to manually encode).

I'll have to check if the same method works on linux as well, though, and if not add some conditional compilation flags. Hopefully I will be able to publish a release fixing this issue on the weekend.

**Comment by supermihi** [comment]
Could you try the current master? It works at least in my testing environment.

**Comment by spiritualized** [comment]
Tested and working correctly under my setup. Thanks!

**Comment by supermihi** [comment]
Great! :) Now there's also an updated windows wheel in the pypi archives.
