### ISSUE TITLE
I/O error when accessing bitrate getter

### ISSUE THREAD

**Issue by spiritualized** [supermihi/pytaglib#30]
I'm occasionally getting an exception thrown when evaluating the bitrate field. I cannot reliably reproduce the issue, it seems to happen randomly once every ~2000 files along the same (read-only) code path. I have ensured that I am not closing the file at any point after opening. Using Python 3.5.2 with 

Traceback (most recent call last):
  File "test.py", line 44, in check_bitrates
    bitrate = track.metadata.bitrate
  File "src\taglib.pyx", line 178, in taglib.File.bitrate.__get__ (src\taglib.cpp:2891)
ValueError: I/O operation on closed file.

**Comment by supermihi** [comment]
That error is raised after `taglib.File.close()` was called on a file – note that the audio property fields (bitrate, channels, etc.) are read from the underlying C++ `TagLib` object on demand, such that the file has to be open when calling these properties.
Does this explain your issue?

**Comment by supermihi** [comment]
Assuming issue is resolved.
