### ISSUE TITLE
pytaglib cannot read FLAC files with zero-length seektables

### ISSUE THREAD

**Issue by larryhastings** [supermihi/pytaglib#35]
If pytaglib attempts to read tags from a FLAC file, and that FLAC file contains a "seektable" metadata block with zero entries, pytaglib will fail with an generic "OSError".  Reading this file with taglib directly works fine.

Github doesn't allow attaching FLAC files, so I've attached "zero.flac" in Base64 encoding.  To decode on a Linux box, use "base64 -d < zero.flac.base64.txt > zero.flac".

[zero.flac.base64.txt](https://github.com/supermihi/pytaglib/files/1083086/zero.flac.base64.txt)

Simply attempting to read from this file fails:
```
    >>> import taglib
    >>> taglib.File("zero.flac")
    Traceback (most recent call last):
      File "zero.py", line 3, in <module>
        f = taglib.File("zero.flac")
      File "src/taglib.pyx", line 82, in taglib.File.__cinit__ (src/taglib.cpp:1609)
    OSError: Could not read file zero.flac

```

I assure you this is a real problem.  I had this problem with all the FLAC releases from the "Project Sidologie" Kickstarter:

https://www.kickstarter.com/projects/c64audio/project-sidologie-jarre-style-commodore-64-music-r

Relevant version numbers:
  * pytaglib version: current Github head (46483948413c1330c036240ed89429a1c6905843
  * taglib version used by pytaglib: "1.11.1-0.1ubuntu2" (current version on Ubuntu GNOME 17.04 64-bit)

Note: Taglib issue could have fixed this since 1.11.1 was tagged last October.  When I tested against Taglib directly, I built against the current version of Taglib from Github, and made a quick command-line tool to dump the artist info.  That worked.  I couldn't figure out how to get pytaglib to use that version of taglib, though--it always linked against the system one first.

**Comment by supermihi** [comment]
Thank you for your detailed report. I can reproduce the problem, also using `taglib-1.11.1`. Apparently, you are experiencing [this](https://github.com/taglib/taglib/pull/791) taglib bug, which was fixed but is not yet contained in any release.

You should be able however to use the current github head from taglib together with pytaglib, because no binary-incompatible changes have been introduced on `master`. Simply override the library search path to where your self-built `libtag.so` is, e.g.:

    LD_LIBRARY_PATH="." python test.py

**Comment by larryhastings** [comment]
I can confirm that running against a current taglib from Github fixes the problem.  The tricky part was figuring how how to tickle taglib into building the shared libraries--I eventually hit on "ccmake".

**Comment by supermihi** [comment]
Great, I'm glad that you could fix the problem! :)
