### ISSUE TITLE
Build fails on mac os x 10.13.3 (and Fedora)

### ISSUE THREAD

**Issue by meteopascal** [supermihi/pytaglib#42]
Below is the full session.
The same errror happens with python 2.7.14 and 3.6.4, both installed by brew.

I've also seen this error reported on fedora at [https://stackoverflow.com/questions/48511211/pip-installing-pytaglib-error](https://stackoverflow.com/questions/48511211/pip-installing-pytaglib-error)

--- cut here ---
$ pip install -U pytaglib

Collecting pytaglib
  Using cached pytaglib-1.4.2.tar.gz
Requirement already up-to-date: Cython in /usr/local/lib/python2.7/site-packages (from pytaglib)
Building wheels for collected packages: pytaglib
  Running setup.py bdist_wheel for pytaglib ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/4p/7pvh1nkh8xj541001s71ngr000015y/T/pip-build-TC_ry4/pytaglib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/4p/7pvh1nkh8xj541001s71ngr000015y/T/tmpWrufLxpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.13-x86_64-2.7
  copying src/pyprinttags.py -> build/lib.macosx-10.13-x86_64-2.7
  running build_ext
  building 'taglib' extension
  creating build/temp.macosx-10.13-x86_64-2.7
  creating build/temp.macosx-10.13-x86_64-2.7/src
  clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/taglib.cpp -o build/temp.macosx-10.13-x86_64-2.7/src/taglib.o
  src/taglib.cpp:1736:41: error: cannot initialize a parameter of type 'FileName' (aka 'const char *') with an lvalue of type 'const Py_UNICODE *' (aka 'const unsigned short *')
      __pyx_t_6 = TagLib::FileRef::create(__pyx_t_5);
                                          ^~~~~~~~~
  /usr/local/include/taglib/fileref.h:273:34: note: passing argument to parameter 'fileName' here
      static File *create(FileName fileName,
                                   ^
  1 error generated.
  error: command 'clang' failed with exit status 1

**Comment by candh** [comment]
Same issue. Fails on macOS 10.13.2 too.. 😢

**Comment by nbeversl** [comment]
Also same issue. OS 10.12.6

 running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    copying src/pyprinttags.py -> build/lib.macosx-10.6-intel-3.6
    running build_ext
    building 'taglib' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/src
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/taglib.cpp -o build/temp.macosx-10.6-intel-3.6/src/taglib.o
    src/taglib.cpp:1736:41: error: cannot initialize a parameter of type 'FileName' (aka 'const char *') with an lvalue of type 'const Py_UNICODE *' (aka 'const wchar_t *')
        __pyx_t_6 = TagLib::FileRef::create(__pyx_t_5);
                                            ^~~~~~~~~
    /usr/local/include/taglib/fileref.h:273:34: note: passing argument to parameter 'fileName' here
        static File *create(FileName fileName,
                                     ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/8d/byr62r6x43n3vfs4v_cjm2n80000gn/T/pip-build-jzkt6fw3/pytaglib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/8d/byr62r6x43n3vfs4v_cjm2n80000gn/T/pip-zgy1o70h-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8d/byr62r6x43n3vfs4v_cjm2n80000gn/T/pip-build-jzkt6fw3/pytaglib/

**Comment by supermihi** [comment]
Sorry guys, turns out I accidentally uploaded a `taglib.cpp` precompiled for Windows only to PyPI. Can you please check the current version `v1.4.3`?

**Comment by griswolf** [comment]
Solved for me by supermihi 3 hours ago. Yay!

**Comment by supermihi** [comment]
Great, so I consider this closed. Sorry again for the inconvenience.

@meteopascal @nbeversl @candh please don't hesitate to reopen if the issue remains.
