### ISSUE TITLE
Tags are not saved (v1.4.1)

### ISSUE THREAD

**Issue by andbandss** [supermihi/pytaglib#44]
Due to an issue documented earlier, I am using the previous version of pytaglib. I found that I am not able to consistently save new tags to a FLAC file. Here is the output from a python interactive session:
```
>>> import taglib
>>> test_file = taglib.File("/home/andrew/Desktop/Cypress Hill/2000 - Skull & Bones Skull Disc/01 - Intro.flac")
>>> test_file.tags
{'TITLE': ['Intro'], 'ENCODER': ['Rubyripper 0.7.0rc1'], 'DISCID': ['98099e0b'], 'ARTIST': ['Cypress Hill'], 'ALBUM': ['Skull & Bones: Skull Disc'], 'TRACKTOTAL': ['11'], 'GENRE': ['Rock'], 'DATE': ['2000'], 'TRACKNUMBER': ['1']}
>>> test_file.tags["ALBUM"] = ["Skull & Bones"]
>>> test_file.tags
{'TITLE': ['Intro'], 'ENCODER': ['Rubyripper 0.7.0rc1'], 'DISCID': ['98099e0b'], 'ARTIST': ['Cypress Hill'], 'ALBUM': ['Skull & Bones'], 'TRACKTOTAL': ['11'], 'GENRE': ['Rock'], 'DATE': ['2000'], 'TRACKNUMBER': ['1']}
```

In this example, I attempt to change the "ALBUM" tag. It appears to work, however, I closed this session and opened another and this was the output:

```
>>> import taglib
>>> test_file = taglib.File("/home/andrew/Desktop/Cypress Hill/2000 - Skull & Bones Skull Disc/01 - Intro.flac")
>>> test_file.tags
{'TITLE': ['Intro'], 'ARTIST': ['Cypress Hill'], 'TRACKTOTAL': ['11'], 'DISCID': ['98099e0b'], 'DATE': ['2000'], 'ALBUM': ['Skull & Bones: Skull Disc'], 'GENRE': ['Rock'], 'ENCODER': ['Rubyripper 0.7.0rc1'], 'TRACKNUMBER': ['1']}
```

The "ALBUM" tag has reverted. This happens about nine times in ten, but occasionally I do actually get a tag to save. I have not yet found any pattern in which tags save and which do not. I suspect this an issue with TagLib itself because this vaguely resembles one or two earlier issues with this package. I thought I would raise the issue first, however, as pytaglib is my interface with TagLib and I acquired TagLib through pip with the pytaglib installation.

**Comment by supermihi** [comment]
Did you call `test_file.save()` after changing the tags?

**Comment by supermihi** [comment]
Closing due to lack of information / assuming previous comment fixed the issue.
