### ISSUE TITLE
Any way to embed an album cover into the file?

### ISSUE THREAD

**Issue by lemos1235** [supermihi/pytaglib#45]
I can not find the album cover when using this tool, either embed an album cover. By the way, other tools only support few file formats(like 'mp3', not support the 'flac '). Is there any solutions?

**Comment by supermihi** [comment]
Album covers are not supported by this library because the underlying taglib library does not yet provide a uniform interface form album covers.
There are plans to add such a feature to taglib version 2.0 which is yet to be officially released; once it is, we can upgrade pytaglib accordingly.
