### ISSUE TITLE
Windows: compilation error on Python 3.7 with VS 2017 Community

### ISSUE THREAD

**Issue by queengooborg** [supermihi/pytaglib#49]
Seems like this has been an issue that has occurred for an older version of this library, as described in issue #37.  Everything that's happening is pretty much described in that issue (however I decided to open up a new issue since it's a new version of the library and whatnot).

Just in case, here's the log for my runtime:
```
E:\Program Files\Microsoft Visual Studio\2017\Community>pip install pytaglib
Collecting pytaglib
  Using cached https://files.pythonhosted.org/packages/c7/f0/c6d15860c6ab5953320edd36b5050e9d813d025bd49563ef7a24154b69c7/pytaglib-1.4.3.tar.gz
Requirement already satisfied: Cython in c:\python37\lib\site-packages (from pytaglib) (0.28.5)
Installing collected packages: pytaglib
  Running setup.py install for pytaglib ... error
    Complete output from command c:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\vinyl\\AppData\\Local\\Temp\\pip-install-9owdogvm\\pytaglib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vinyl\AppData\Local\Temp\pip-record-mp9puh1j\install-record.txt --single-version-externally-managed --compile:
    cythonizing taglib.pyx ...
    src\taglib.pyx: cannot find cimported module 'ctypes'
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying src\pyprinttags.py -> build\lib.win-amd64-3.7
    running build_ext
    building 'taglib' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    E:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DTAGLIB_STATIC -IC:\Libraries\taglib\include -Ic:\python37\include -Ic:\python37\include "-IE:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" "-IE:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tpsrc\taglib.cpp /Fobuild\temp.win-amd64-3.7\Release\src\taglib.obj
    taglib.cpp
    src\taglib.cpp(615): fatal error C1083: Cannot open include file: 'taglib/tstring.h': No such file or directory
    error: command 'E:\\Program Files\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\vinyl\\AppData\\Local\\Temp\\pip-install-9owdogvm\\pytaglib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vinyl\AppData\Local\Temp\pip-record-mp9puh1j\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\vinyl\AppData\Local\Temp\pip-install-9owdogvm\pytaglib\
```

Thank you in advance!

**Comment by jxoesneon** [comment]
I get the same error when ruining **_pip install pytaglib_** .... is there something preventing the full resolution of this issue? from research it looks like it's been an ongoing issue for a while, I understand something going wrong when building from source, but should the pip install be as painless as possible?

**Comment by vinyldarkscratch** [comment]
@jxoesneon What it looks like is simply the lack of a compiled version for Python 3.7 on PyPi, which is causing `pip` to fallback to compiling from source.  However, doing a little bit of research, it seems that neither `pytaglib` 1.4.3 or 1.4.4 have any compiled versions anyways.

@supermihi By the way, if you'd like some assistance in maintaining compiled versions of pytaglib (especially for macOS), I'm happy to lend a hand.  ;)

**Comment by supermihi** [comment]
Yes, the problem is that, on windows, "on-the-fly" compilation via `pip` is not possible as it is on unix systems (or at leas, way more complex). Hence, I am uploading binary wheels for windows.

Since I do not have a private windows PC, it is relatively uncomfortable to generate the windows builds. Any help is appreciated!
Concerning mac OS, I don't have any experience. As far as I understood, the on-demand build is possible using `brew`, but of course I also appreciate any help here. Don't you suffer from #29?

**Comment by vinyldarkscratch** [comment]
It can definitely be a pain to compile anything on Windows, haha, which is always why wheels are super helpful for Windows platforms.  I'm always happy to help however I can!  I caved in and just kept all my development work on macOS instead for the time being, though my job as a software porter requires me to be able to compile on Windows anyways -- I'll be giving compiling `pytaglib` a shot soon.  :wink:

As far as macOS, it's practically the same as via a Linux machine, just using `brew` or `port` rather than `apt` or `rpm`, and building from source on the fly works perfectly after a `brew/port install taglib`, though it's always nice to have pre-compiled versions at the ready (which is the route Homebrew has been taking recently).  Actually, #29 isn't an issue for me, to be honest -- I'm running macOS Mojave but have been using `pytaglib` since High Sierra with no issues (both on Python 2.7).

**Comment by supermihi** [comment]
Nice to hear. Windows compilation as described in the README of this repository did work the last time I checked, but it took me quite a while to find out ... :)
I can do the Windows wheels on my work laptop (wtih some delay …), but definitely not for Mac OS, so I'd be very grateful for your help there.

**Comment by vinyldarkscratch** [comment]
An idea just came to mind.  Since you're already using Travis CI, why not utilize it to upload wheels for macOS and Linux, and then possibly use CircleCI or something for Windows?  Travis CI [already has PyPi deployment support](https://docs.travis-ci.com/user/deployment/pypi/), and it might help by eliminating a step on your end!

**Comment by supermihi** [comment]
Great idea. Let's see if I will be able to find the time to pursue it. ;-)

**Comment by marian-code** [comment]
I too tried to compile pytaglib for python 3.7. But I am using Visual studio 16 2019. By folowing your instructions in README for win compilation I can build taglib without problems. Altough I had to modify cmake command to:
`cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=".\taglib-install"`
and use x64 Native Tools Command Prompt for VS 2019. MSBuild also passes without errors. But when I try to run `python setup.py build` I get errors from link.exe - fatal error LNK1120: 3 unresolved externals. The output of all three steps is in the attached gist:
[https://gist.github.com/marian-code/1f6678eaa5f4d169b29849583c498e95](url)
If someone has any advice on how to proceed I would greatly appreciate it.

**Comment by ramb2** [comment]
I successfully compiled and installed in Python 3.8 on windows. I followed the instructions. Used VS2015 x64 Native Tools Command Prompt. It could not find certain files, so I copied those to where it wanted them. Copied the taglib directory to "C:\Libraries\taglib" and to the src directory. Maybe this is helpful for somebody.

**Comment by IvoryLu** [comment]
I was using Python 3.7 (64 bit)and followed the instructions. I got several mismatch errors like:
tag.lib(flacmetadatablock.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in taglib.obj. 
Does anyone have any idea on how to solve these issues? Thanks in advance.

**Comment by marian-code** [comment]
I know this is probably not the advice you were looking for, but after several unsuccessful attempts to compile pytaglib I just switched to [mutagen](https://mutagen.readthedocs.io/en/latest/). It is more low level so a bit harder to learn but it is generally more powerfull and can be installed via pip as it is pure python.

**Comment by supermihi** [comment]
Meanwhile there are binary wheels for windows, suing Python 3.7 and 3.8. Could anyone affected by this issue please try if those work? 

There is now also a build script `windows/build_win.py` in this repository. Provided the MVSC compiler is installed, that script should automatically build pytaglib for the python version it is called with.

**Comment by devdave** [comment]
@supermihi I think the windows/build_win.py script has gotten me a lot further toward being able to build pytaglib but I ran into a security issue like this 

```*** building pytaglib ...
cythonizing taglib.pyx ...
[1/1] Cythonizing src\taglib.pyx
running install
error: SandboxViolation: open('C:\\Python39\\Lib\\site-packages\\test-easy-install-2900.write-test', 'w') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

```

I am currently looking into EasyInstall to see how I can convince it to calm down and just go ahead and make the new files.    Even when running as super user/administrator I hit that sandbox check.

**Comment by devdave** [comment]
Not a great fix but a "works for now" fix to the sandbox problem.

I modified `build_win.py` slightly like so:

```python
def pytaglib_build():
    print("*** building pytaglib ...")
    print(f"\tTAGLIB_HOME={str(taglib_out)}")
    print(f"\tRepository root: {repository_root}")
    os.environ['TAGLIB_HOME'] = str(taglib_out)
    os.environ['PYTAGLIB_CYTHONIZE'] = '1'
    os.chdir(repository_root)
    return
```

From the command line I did `set TAGLIB_HOME={what pytaglib_build printed}` and then from command line `setup install` followed by running pytest and everything worked.    The build_win.py script did 99% of the work but the security sandbox check prevents it from automatically installing pytaglib into the system or virtual environment site packages.

**Comment by Yunoinsky** [comment]
For ERROR: LNK (link error), you can try to replace taglib-x86-win with taglib-x64-win.

**Comment by supermihi** [comment]
Dear participants of this discussion,
it has taken extremely long, but today I can finally announce auto-generated binary wheels for windows from the GitHub actions CI, starting from v1.5.0 which was released a few seconds ago.
If you are still interested in this project, please give it a try! Binaries are built for Python 3.8, 3.9 and 3.10, x64 only.
