### ISSUE TITLE
Windows: abnormal exit

### ISSUE THREAD

**Issue by Buzzroid** [supermihi/pytaglib#55]
D:\                                                                                                
λ python                                                                                           
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32  
Type "help", "copyright", "credits" or "license" for more information.                             
>>> import taglib                                                                                  
>>> song = taglib.File("D:/c.flac")                                                                
************ The above takes few seconds, then does nothing but exit *******************                                                                                                   
D:\

**Comment by supermihi** [comment]
Thanks for your report. Windows support is rather experimental because I don't regularly use that operating system. I have however recently installed Win10 on my home desktop, will test pytaglib with newest python asap!

**Comment by supermihi** [comment]
Closing because of age. Recent versions work fine in windows CI.
