### ISSUE TITLE
song = taglib.File("/path/to/my/file.mp3") throws NameError: name 'fspath' is not defined

### ISSUE THREAD

**Issue by varun952** [supermihi/pytaglib#57]
I am trying to run basic example in linux environment: 
I have installed development headers  of pytaglib and also python-dev headers, but after running following lines I get and exception : 
<code>import taglib </code>
<code>song = taglib.File("/path/to/my/file.mp3")</code>

Exception:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/taglib.pyx", line 72, in taglib.File.__cinit__
NameError: name 'fspath' is not defined

**Comment by varun952** [comment]
It turns out when I ran same code with python3 it works. But I was expecting it to work with python2.7
Is there a way where I can do this?

**Comment by supermihi** [comment]
Which version are you using? AFAIK I newer added the `fspath` call which would fix #40. Maybe you accidentally checked out [this fork](https://github.com/vinyldarkscratch/pytaglib/commit/8edfc3dfe0778b39bdd6a0c6145e7b1c554496bb)?

**Comment by varun952** [comment]
I installed pytaglib from standard command for version 1.4.4

**Comment by supermihi** [comment]
Thanks for reporting. Apparently I forgot to regenerate the shipped `taglib.cpp` before packing the release, such that an uncommited test version of the file is contained in the published file. :-( Will upload a fixed v1.4.5 ASAP!

**Comment by supermihi** [comment]
Please try v1.4.5 just released to PyPI!

**Comment by varun952** [comment]
I am trying fresh , while installing the version 1.4.5 it is throwing an error in pip.log

<code>
   Removing temporary dir /tmp/pip_build_root...
 Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pytaglib
 Exception information:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
     status = self.run(options, args)
   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
     req_to_install.run_egg_info()
   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
     command_desc='python setup.py egg_info')
   File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
     % (command_desc, proc.returncode, cwd))
 InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pytaglib </code>
