### ISSUE TITLE
Using pytaglib to extract tags from audio also give COMMENT:ITUNENORM and COMMENT:ITUNESMPB tags with hex values

### ISSUE THREAD

**Issue by varun952** [supermihi/pytaglib#59]
When tagging audio with itunes, it stores some information like Normalisation or channel rates in tags called COMMENT:, which is actually not a valid information for me after I extract tags from such audio file.
Is there a way in pytaglib , that i dont get these information while extracting?

**Comment by varun952** [comment]
Please refer this for more information on my situation: 
https://stackoverflow.com/questions/55470062/why-audio-files-tagged-with-itunes-player-have-commentitunsmpb-and-commentitun

**Comment by supermihi** [comment]
Sorry, I did not really get the problem. Pytaglib gives you access to all tags in the file; if you are not interested in some of them, you can just ignore them in your userspace application.
