### ISSUE TITLE
Some tags are not being saved on MP4 files

### ISSUE THREAD

**Issue by Cabalist** [supermihi/pytaglib#69]
Hey there.

I'm having some issues applying some tags to an MP4 file.  

macOS 10.14.6
pytaglib 1.4.5
taglib 1.11.1

My code looks like this:

```python
import taglib

workfile =  taglib.File("AC Circuit Analysis.S01E01.mp4")
print(workfile.tags)
workfile.tags['SHOW'] = ["AC Circuit Analysis"]
workfile.tags['TITLE'] = ["What Is Alternating Current"]
workfile.save()
print(workfile.tags)

```

The output of this is:

```
{'TITLE': ['What Is Alternating Current']}
{'TITLE': ['What Is Alternating Current'], 'SHOW': ['AC Circuit Analysis']}
```

I'd expect if I ran this a second I would get this:

```
{'TITLE': ['What Is Alternating Current'], 'SHOW': ['AC Circuit Analysis']}
{'TITLE': ['What Is Alternating Current'], 'SHOW': ['AC Circuit Analysis']}
```

but I don't.   The `SHOW` tag is not being saved in the file.

The `.save()` call only seems to be writing out the `TITLE` tag for me.   After some experimentation I can confirm that `TITLE` is being updated but trying other tags I wasn't able to find one that updates (like `TVEN` and `TVES`) .   If I remove `TITLE` and just try and update `SHOW` I get the same unsaved result.

Is there something about the MP4 spec that I am not aware of that blocks these tags?   Is this more likely an issue with taglib?

**Comment by Cabalist** [comment]
This appears to be a limitation of the taglib library.   I haven't gotten entirely to the bottom of this but `ffmpeg` is capable of writing out the tags as well as some GUI tools like MetaZ.   `pytaglib` can read some of these back but not all.

**Comment by supermihi** [comment]
Thanks. Problems specific to formats and/or tags are always most likely taglib problem, because pytaglib does not treat any tags or file formats in a special way.

Did you check however if the tags that are not saved into the file are contained in the dictionary returned by `.save()`? That, at least, should work, signalling to you that there was a problem in saving these tags.

**Comment by Cabalist** [comment]
The Tags DO appear in the return value of `.save()` but do not appear when the file is re-read.  

I was able to use [mutagen](https://mutagen.readthedocs.io/en/latest/) as a drop in replacement but I've got some concerns about speed going forward.  I believe mutagen does some magic to specifically handle MP4 files. 

Definitely a `taglib` issue.   I'll take things up there.  :) Thanks!
