### ISSUE TITLE
How do I add a tag?

### ISSUE THREAD

**Issue by MarcusJohnson91** [supermihi/pytaglib#70]
I want to open an existing file X.flac, and add a tag who's name is "ITUNESADVISORY" and set it's value to a bool.

How do I do this?

**Comment by supermihi** [comment]
See the README:

```python
>>> import taglib
>>> song = taglib.File("X.flag")
>>> song.tags["ITUNESADVISORY"] = ["1"]
```

Note that there are no `bool` values in most tag specs, only strings; the above example assumes you use the strings `"0"` and `"1"`, which I think is a common way of expressing bools.
