### ISSUE TITLE
Calling pyprinttags from cmd line results in import error

### ISSUE THREAD

**Issue by JamesOwers** [supermihi/pytaglib#71]
To reproduce the error, install via pip in a python 3 environment:

```
$ pyprinttags3
Traceback (most recent call last):
  File "/Users/.../miniconda3/envs/.../bin/pyprinttags3", line 5, in <module>
    from pyprinttags import script
ModuleNotFoundError: No module named 'pyprinttags'
```

**Comment by JamesOwers** [comment]
Can confirm this error goes away if you install from source (the current `setup.py` does list `pyprinttags` as a module)

**Comment by supermihi** [comment]
Thanks for the report. I will upload a fixed package to pypi asap!

**Comment by JamesOwers** [comment]
No problem and thank you.

**Comment by supermihi** [comment]
Please try again with v1.4.6 just released on pypi.
