### ISSUE TITLE
'error: Microsoft Visual C++ 14.0 is required.' when installing

### ISSUE THREAD

**Issue by teadrinker2015** [supermihi/pytaglib#75]
I use 'pip install pytaglib' on windows10.
Does that mean I have to download visual studio?

`Running setup.py install for pytaglib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\gaoxin\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gaoxin\\AppData\\Local\\Temp\\pip-install-_y7w5pxb\\pytaglib\\setup.py'"'"'; __file__='"'"'C:\\Users\\gaoxin\\AppData\\Local\\Temp\\pip-install-_y7w5pxb\\pytaglib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\gaoxin\AppData\Local\Temp\pip-record-px_9i2ti\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\gaoxin\appdata\local\programs\python\python37-32\Include\pytaglib'
         cwd: C:\Users\gaoxin\AppData\Local\Temp\pip-install-_y7w5pxb\pytaglib\
    Complete output (12 lines):
    cythonizing taglib.pyx ...
    running install
    running build
    running build_py
    file src\pytaglib.py (for module pytaglib) not found
    creating build
    creating build\lib.win32-3.7
    copying src\pyprinttags.py -> build\lib.win32-3.7
    file src\pytaglib.py (for module pytaglib) not found
    running build_ext
    building 'taglib' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\gaoxin\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gaoxin\\AppData\\Local\\Temp\\pip-install-_y7w5pxb\\pytaglib\\setup.py'"'"'; __file__='"'"'C:\\Users\\gaoxin\\AppData\\Local\\Temp\\pip-install-_y7w5pxb\\pytaglib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\gaoxin\AppData\Local\Temp\pip-record-px_9i2ti\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\gaoxin\appdata\local\programs\python\python37-32\Include\pytaglib' Check the logs for full command output.`

**Comment by supermihi** [comment]
Yes and no. You need visual studio (or at least the VS buils tools) to *build* pytaglib on Windows.

Because that is very cumbersome, I have updloaded some binary wheels for Windows, not yet however for the current versions of Python and pytaglib.

I have started to develop a script that automates the build & upload process. Hopefully I can provide up-to-date wheels in a few days.

Am 18. Mai 2020 13:46:03 MESZ schrieb teadrinker2015 <notifications@github.com>:

**Comment by supermihi** [comment]
Wheels are now uploaded for python 3.7 and 3.8, both x64 and x32. They should be automatically installed with `pip install pytaglib` on windows. Could you give it a try?

**Comment by supermihi** [comment]
assuming it is working now
