### ISSUE TITLE
Installing pytaglib ImportError: DLL load failed while importing taglib:

### ISSUE THREAD

**Issue by support2019mp** [supermihi/pytaglib#79]
Hi! 
I'm on Windows 10, Python 3.8 and pip 20.1.1.
installing pytaglib, pip install pytaglib 
get this error when import taglib : ImportError: DLL load failed while importing taglib
It happens when installing Python 3.8 with windows installer (Windows x86-64 executable installer).
Reinstalled with Windows x86 executable installer, and pip install pytaglib again, and works fine.
Thank you

**Comment by supermihi** [comment]
Hi,
interesting, I just checked with Python 3.8.3 x64 on Windows and everything works fine. Which python version are you using exactly?

**Comment by support2019mp** [comment]
Hi!
Python 3.8.0
Thank you

**Comment by supermihi** [comment]
Could you try upgrading to 3.8.3? The binary wheel on pypi was probably buit with 3.8.2, so there might be some problems when using an earlier 3.8 subrelease.

**Comment by supermihi** [comment]
closing due to missing information
