### ISSUE TITLE
Windows10 installing

### ISSUE THREAD

**Issue by BriansGithubName** [supermihi/pytaglib#80]
I have been unsuccessful in trying to install pytaglib. First I tried pip which failed. (C:\WINDOWS\system32>pip install pytaglib
Collecting pytaglib
  Using cached pytaglib-1.4.6.tar.gz (468 kB)
Using legacy 'setup.py install' for pytaglib, since package 'wheel' is not installed.
Installing collected packages: pytaglib
    Running setup.py install for pytaglib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\b_m_d\\AppData\\Local\\Temp\\pip-install-ds40lklk\\pytaglib_0e628745c65f482b9b63582026147c8b\\setup.py'"'"'; __file__='"'"'C:\\Users\\b_m_d\\AppData\\Local\\Temp\\pip-install-ds40lklk\\pytaglib_0e628745c65f482b9b63582026147c8b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\b_m_d\AppData\Local\Temp\pip-record-p2ulm8ms\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python39\Include\pytaglib'
         cwd: C:\Users\b_m_d\AppData\Local\Temp\pip-install-ds40lklk\pytaglib_0e628745c65f482b9b63582026147c8b\
    Complete output (12 lines):
    cythonizing taglib.pyx ...
    running install
    running build
    running build_py
    file src\pytaglib.py (for module pytaglib) not found
    creating build
    creating build\lib.win-amd64-3.9
    copying src\pyprinttags.py -> build\lib.win-amd64-3.9
    file src\pytaglib.py (for module pytaglib) not found
    running build_ext
    building 'taglib' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\b_m_d\\AppData\\Local\\Temp\\pip-install-ds40lklk\\pytaglib_0e628745c65f482b9b63582026147c8b\\setup.py'"'"'; __file__='"'"'C:\\Users\\b_m_d\\AppData\\Local\\Temp\\pip-install-ds40lklk\\pytaglib_0e628745c65f482b9b63582026147c8b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\b_m_d\AppData\Local\Temp\pip-record-p2ulm8ms\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python39\Include\pytaglib' Check the logs for full command output.

Then I tried easy_install with the egg sand it failed (ImportError: cannot import name 'main' from 'setuptools.command.easy_install' ).

 Finally I tried the May 2020 wheel version with no success. (C:\Program Files\Python39\Scripts>py -m pip install G:\Projects\Python\MusicMan\pytaglib-1.4.6-cp38-cp38-win_amd64.whl
ERROR: pytaglib-1.4.6-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.)

Since I'm fairly new to all things Python, the problem may be simple ignorance on my part. . .

**Comment by BriansGithubName** [comment]
The Visual C++ 14 IS installed (both 32 and 64 bit versions)

**Comment by supermihi** [comment]
Hi @BriansGithubName, since you closed the issue I assume that you were able to resolve it?
