### ISSUE TITLE
support for id3v2.3

### ISSUE THREAD

**Issue by ludgerheck** [supermihi/pytaglib#99]
seeing that there are players that don't support id3v2.4 it would be nice if one could call save with an option "idv2.3"
as in mpegfile->save( TagLib::MPEG::File::AllTags, true, 3).

Maybe I just haven't found how to do it.

**Comment by supermihi** [comment]
Thank you for your request. Since pytaglib intentionally has a minimal API that abstracts from specific file formats, such a feature is not within the scope of this package.

I suggest you have a look at the [mutagen](https://github.com/quodlibet/mutagen) package instead.
